{% set lower_bound_version = "1.75.0" %}
{% set version_stable = "1.76.0" %}
{% set version = version_stable + ".dev20231115" %}

package:
  name: rust_{{ target_platform }}-suite
  version: {{ version }}

build:
  number: 0
  skip: True  # [s390x]

outputs:
  - name: rust_{{ target_platform }}
    script: build.sh  # [unix]
    script: bld-msvc.bat  # [win]
    build:
      skip: True  # [win and int(float(vc)) != 14]
      run_exports: # [osx and x86_64]
          strong_constrains: # [osx and x86_64]
            - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]
    requirements:
      run:
        - rust >{{ lower_bound_version }},<{{ version_stable }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    test:
      files:
        - forge_test.sh  # [not win]
      commands:
        - rustc --help
        - cargo --help
        - time bash ./forge_test.sh  # [not win]
  - name: rust-gnu_{{ target_platform }}  # [win]
    script: bld-gnu.bat  # [win]
    requirements:  # [win]
      run:  # [win]
        - rust-gnu >{{ lower_bound_version }},<{{ version_stable }}  # [win]
        - m2w64-toolchain  # [win]
    test:  # [win]
      files:  # [win]
        - forge_test.sh  # [win]
      commands:  # [win]
        - rustc --help  # [win]
        - cargo --help  # [win]

about:
  home: https://www.rust-lang.org
  summary: A safe systems programming language (conda activation scripts)
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Rust is a systems programming language that runs blazingly fast,
    prevents segfaults, and guarantees thread safety.
  doc_url: https://www.rust-lang.org/learn
  dev_url: https://github.com/rust-lang/rust

extra:
  recipe-maintainers:
    - mingwandroid
  # For activation scripts, compilers must be in the run section
  # The compiler function is inappropriate here because a specific version is needed
  skip-lints:
    - compilers_must_be_in_build
    - should_use_compilers
